name: Deploy to GitHub Pages

on:
  push:
    branches:
      - repositorio-base  # Cambia esto a tu rama que contiene el proyecto real

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permiso para escribir en el repositorio

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate config.js
        env:
          EMAILJS_USER_ID: ${{ secrets.EMAILJS_USER_ID }}
          EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
          EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
        run: |
          echo "const emailConfig = {" > config.js
          echo "    userId: '$EMAILJS_USER_ID'," >> config.js
          echo "    templateId: '$EMAILJS_TEMPLATE_ID'," >> config.js
          echo "    serviceId: '$EMAILJS_SERVICE_ID'" >> config.js
          echo "};" >> config.js

      - name: List files in publish directory
        run: ls -la ./  # Esto listará los archivos en la raíz del repositorio

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Asegúrate de que esto sea correcto
